### ISSUE TITLE
blockui load twice !!!

### ISSUE THREAD

**Issue by allaghi** [realdah/vue-blockui#5]
Hello, 
Have a nice day,
I am using blockui when trying to fetch data from server and it works fine , but when I do submit to the form it load again , even when I let loading = false.?

**Comment by realdah** [comment]
@allaghi the blockui component is depending on native vue show/hide mechanism to show or hide.
Can you please try to show the value of **loading** somewhere in your page so that you can diagnose this problem?

**Comment by realdah** [comment]
Closed due to inactivity.
