### ISSUE TITLE
Unable to Override the Css of Block UI

### ISSUE THREAD

**Issue by Serenityxl** [realdah/vue-blockui#7]
HI, In your documentation, you say that we can override the CSS of the Block UI component. I've tried by many way to change the color of the background of the loading div of your component and get rid of the box-shadow but with no success. The documentation isn't really clear on that purpose.

I've tried by  doing this
```
<style scoped>
  .loading-container.loading {
    color:red !important;
        box-shadow: none;
    }
</style>
```

this
```
   .loading {
    color:red !important;
        box-shadow: none;
    }
```
this
```
   <BlockUI >
         <div class="loading">
                <tree-loader></tree-loader>
          </div>
  </BlockUI>
```
And even this
```
<BlockUI style="box-shadow: none; color: red;" >
                <tree-loader></tree-loader>
</BlockUI>
```

I don't know if it's just a bug or that there is no real  way to override the css other than  pure javascript.
The documentation isn't clear on that topic

Otherwise the  tool is really great Thank you!

**Comment by realdah** [comment]
sorry, just saw your ticket in here.....

I think you should be aware that you can't use below
```
.loading-container.loading
```

instead, you should use this as css scoping.
```
.loading-container .loading
```
